# playbooks/create_k3s_scripts/destroy_k3s_other_master_nodes.yml
- name: 4. Destroy Other Master Nodes
  hosts: other_master_nodes
  become: true

  vars:
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa

  tasks:
    - name: 4.1 Execute K3s Node Destruction
      template:
        src: ../../templates/destroy_k3s_node.j2
        dest: /opt/k3s/destroy_k3s_master_node.sh
      vars:
        node_type: "MASTER_NODE"

    - name: 4.2 Change file permissions to 775
      file:
        path: /opt/k3s/destroy_k3s_master_node.sh
        mode: "775"
